/* See LICENSE file for copyright and license info. */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "../ledgerplot.h"
#include "../c_generic/functions.h"
#include "../c_generic/enum.h"
#include "../enum.h"
#include "income_vs_expenses.h"


#define MAX_CMD_LENGTH 512

#ifndef NDEBUG
static const char *f_gnuplot_ive = "/usr/local/share/ledgerplot/gnuplot/gp_income_vs_expenses.gnu";
#else
static const char *f_gnuplot_ive = "gnuplot/gp_income_vs_expenses.gnu";
#endif
/*static char *f_cmd =
    "ledger -f %s --strict bal --real -X EUR -H -s %s -d \"T&l<=1\" expenses income | grep -Eo '[-0-9][0-9\\.]{1,100}'";*/
// TODO: period must be of the form "-M", for a monthly overview
static char *f_cmd_income = "ledger -f %s --strict -j reg --real -X EUR -H ^income %s --collapse --plot-amount-format="%(format_date(date, \"%Y-%m-%d\")) %(abs(quantity(scrub(display_amount))))\n";
// TODO: period must be of the form "-M" for a monthly overview
static char *f_cmd_expenses = "ledger -f %s --strict -j reg --real -X EUR -H ^expenses %s --collapse";
static char *f_gnuplot_ive_cmd = "plot for [COL=STARTCOL:ENDCOL] '%s' u COL:xtic(1) w histogram title columnheader(COL) lc rgb word(COLORS, COL-STARTCOL+1), for [COL=STARTCOL:ENDCOL] '%s' u (column(0)+BOXWIDTH*(COL-STARTCOL+GAPSIZE/2+1)-1.0):COL:COL notitle w labels textcolor rgb \"#839496\"";

/*
 * ive_prepare_data:
 * This function prepares the data to be plotted.
 */
int ive_prepare_data(
    const char *a_input_file,
    FILE *a_output_file0,
    FILE *a_output_file1,
    plot_object *a_plot_object
)
{
    // TODO: Work with 2 output files: 1 for income, 1 for expenses.
    FILE *l_fp;
    char l_cmd[MAX_CMD_LENGTH];
    char l_line_temp[MS_INPUT_LINE];
    char l_line_input[MS_INPUT_LINE];
    char l_line_output[MS_INPUT_LINE]; /* The output line may be just as long. */
    double l_d1;
    double l_d2;
    double l_d3;
    char *l_tmp;
    char l_current_datetime[20];

    memset(l_cmd_income, '\0', sizeof(char) * MAX_CMD_LENGTH);
    memset(l_cmd_expenses, '\0', sizeof(char) * MAX_CMD_LENGTH);
    switch(a_enum_plot_timeframe)
    {
        case weekly:
            //sprintf(l_result, f_cmd_weekly, a_input_file, /* TODO: make  a_current_year a string with the period */a_current_year);
            break;
        case monthly:
            //sprintf(l_result, f_cmd_monthly, a_input_file, /* TODO: make  a_current_year a string with the period */a_current_year);
            break;
        case quarterly:
            //sprintf(l_result, f_cmd_quarterly, a_input_file, a_current_year);
            break;
        default:
            // TODO: l_period must be something like '-b "2015-01-01" -e "2017-01-01"'
            // TODO: change the command. Use something like in the ledger_examplescripts
            snprintf(l_cmd_income, MAX_CMD_LENGTH - 1, f_cmd_income, a_input_file, l_period);
            snprintf(l_cmd_expenses, MAX_CMD_LENGTH - 1, f_cmd_expenses, a_input_file, l_period);
    }

    l_fp = popen(l_cmd_income, "r");
    if (l_fp == NULL)
    {
        fprintf(stderr, "Could not execute ledger command.\n");
        return FAILED;
    }

    *l_line_output = '\0';
    while (fgets(l_line_input, MS_INPUT_LINE, l_fp) != NULL)
    {
        *l_line_temp = '\0'; /* Make sure temp string is empty. */
        trim_whitespace(l_line_temp, l_line_input, MS_INPUT_LINE);
        if (strlen(l_line_output) <= 0)
            sprintf(l_line_output, "%s", l_line_temp);
        else
            sprintf(l_line_output, "%s %s", l_line_output, l_line_temp);
    }
    l_d1 = strtod(l_line_output, &l_tmp);
    l_d2 = -1.0 * strtod(l_tmp, &l_tmp); /* Income is the second number, it's
                                            * always negative in accounting.
                                            * Reverse for correct display in graph.
                                            */
    l_d3 = strtod(l_tmp, NULL);
    //printf("test: l_d1 = %.2f, l_d2 = %.2f, l_d3 = %.2f\n", l_d1, l_d2, l_d3);

    if (pclose(l_fp) == -1)
        fprintf(stderr, "Error reported by pclose().\n");

    /* Initialize tmp file */
    if (i == 0)
    {
        // TODO: move timestamp function in its own module.
        // TODO: make format an enum?
        timestamp(l_current_datetime, "%02d%02d%02d_%02d%02d%02d", sizeof(l_current_datetime));
        fprintf(a_output_file, "# Generated by ledgerplot %s on %s.\n", LEDGERPLOT_VERSION, l_current_datetime);
        fprintf(a_output_file, "year expenses income difference\n");
    }
    /* Write data to tmp file */
    fprintf(a_output_file, "%d %.2lf %.2lf %.2lf\n", l_current_year, l_d1, l_d2, l_d3);
    return 0;
}
