/* See LICENSE file for copyright and license info. */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "../ledgerplot.h"
#include "../c_generic/functions.h"
#include "../c_generic/enum.h"
#include "../enum.h"
#include "income_vs_expenses.h"


#define MAX_CMD_LENGTH 512

static char *f_cmd_assets =
    "ledger -f %s --strict -J -X EUR reg ^assets -M --collapse";
static char *f_cmd_liabilities =
    "ledger -f %s --strict -J -X EUR reg ^liabilities -M --collapse --plot-total-format=\"%(format_date(date, \"%Y-%m-%d\")) %(abs(quantity(scrub(display_total))))\n\"";
// TODO: add -b and -e, to enter startyear and end-year?

/*
 * prepare_temp_file:
 * This function prepares the data to be plotted,
 * in a temporary file that can be read by gnuplot.
 */
int wealthgrowth_prepare_temp_file(
    const char *a_input_file,
    FILE *a_output_file0,
    FILE *a_output_file1,
    uint32_t a_start_year,
    uint32_t a_end_year,
    enum enum_plot_timeframe_t a_enum_plot_timeframe
)
{
    FILE *l_fp;
    char l_cmd0[MAX_CMD_LENGTH];
    char l_cmd1[MAX_CMD_LENGTH];
    char l_line_temp[MS_INPUT_LINE];
    char l_line_input[MS_INPUT_LINE];
    char l_line_output[MS_INPUT_LINE]; /* The output line may be just as long. */
    double l_d1;
    double l_d2;
    double l_d3;
    char *l_tmp;
    char l_current_datetime[20];

    memset(l_cmd, '\0', sizeof(char) * MAX_CMD_LENGTH);
    switch(a_enum_plot_timeframe)
    {
        case daily:
            //sprintf(l_result, f_cmd_daily, a_input_file, a_current_year);
            break;
        case weekly:
            //sprintf(l_result, f_cmd_weekly, a_input_file, a_current_year);
            break;
        case monthly:
            //sprintf(l_result, f_cmd_monthly, a_input_file, a_current_year);
            break;
        default:
            snprintf(l_cmd0, MAX_CMD_LENGTH - 1, f_cmd_assets, a_input_file);
            snprintf(l_cmd1, MAX_CMD_LENGTH - 1, f_cmd_liabilities, a_input_file);
    }

    l_fp = popen(l_cmd0, "r");
    if (l_fp == NULL)
    {
        fprintf(stderr, "Could not execute ledger command %s.\n", l_cmd0);
        return FAILED;
    }

    *l_line_output = '\0';
    while (fgets(l_line_input, MS_INPUT_LINE, l_fp) != NULL)
    {
        *l_line_temp = '\0'; /* Make sure temp string is empty. */
        trim_whitespace(l_line_temp, l_line_input, MS_INPUT_LINE);
        if (strlen(l_line_output) <= 0)
            sprintf(l_line_output, "%s", l_line_temp);
        else
            sprintf(l_line_output, "%s %s", l_line_output, l_line_temp);
    }
    /*l_d1 = strtod(l_line_output, &l_tmp);
    l_d2 = -1.0 * strtod(l_tmp, &l_tmp);
    l_d3 = strtod(l_tmp, NULL);*/
    //printf("test: l_d1 = %.2f, l_d2 = %.2f, l_d3 = %.2f\n", l_d1, l_d2, l_d3);

    // TODO: test output of the commands directly in terminal, to see what we need to put here.
    // TODO: Extract this part, so we can call it again for the second command.
    // TODO: Think about how to implement the date start/end + yearly/monthly/... options.
    if (pclose(l_fp) == -1)
        fprintf(stderr, "Error reported by pclose().\n");

    /* Initialize tmp file */
    if (i == 0)
    {
        // TODO: move timestamp function in its own module.
        // TODO: make format an enum?
        timestamp(l_current_datetime, "%02d%02d%02d_%02d%02d%02d", sizeof(l_current_datetime));
        fprintf(a_output_file0, "# Generated by ledgerplot %s on %s.\n", LEDGERPLOT_VERSION, l_current_datetime);
        fprintf(a_output_file0, "year expenses income difference\n");
    }
    /* Write data to tmp file */
    fprintf(a_output_file0, "%d %.2lf %.2lf %.2lf\n", l_current_year, l_d1, l_d2, l_d3);
    return 0;
}
